export const FETCH_INSTITUTIONS_REQUEST = 'FETCH_INSTITUTIONS_REQUEST';
export const FETCH_INSTITUTIONS_SUCCESS = 'FETCH_INSTITUTIONS_SUCCESS';
export const FETCH_INSTITUTIONS_FAILURE = 'FETCH_INSTITUTIONS_FAILURE';

export const DELETE_INSTITUTION_REQUEST = 'DELETE_INSTITUTION_REQUEST';
export const DELETE_INSTITUTION_SUCCESS = 'DELETE_INSTITUTION_SUCCESS';
export const DELETE_INSTITUTION_FAILURE = 'DELETE_INSTITUTION_FAILURE';

export const UPDATE_INSTITUTION_REQUEST = 'UPDATE_INSTITUTION_REQUEST';
export const UPDATE_INSTITUTION_SUCCESS = 'UPDATE_INSTITUTION_SUCCESS';
export const UPDATE_INSTITUTION_FAILURE = 'UPDATE_INSTITUTION_FAILURE';

export const INSTITUTION_ASSIGN_ADMIN_REQUEST = 'INSTITUTION_ASSIGN_ADMIN_REQUEST';
export const INSTITUTION_ASSIGN_ADMIN_SUCCESS = 'INSTITUTION_ASSIGN_ADMIN_SUCCESS';
export const INSTITUTION_ASSIGN_ADMIN_FAILURE = 'INSTITUTION_ASSIGN_ADMIN_FAILURE';

export const CREATE_INSTITUTION_REQUEST = 'CREATE_INSTITUTION_REQUEST';
export const CREATE_INSTITUTION_SUCCESS = 'CREATE_INSTITUTION_SUCCESS';
export const CREATE_INSTITUTION_FAILURE = 'CREATE_INSTITUTION_FAILURE';
