export const FETCH_INSTITUTIONS_REQUEST = 'FETCH_INSTITUTIONS_REQUEST';
export const FETCH_INSTITUTIONS_SUCCESS = 'FETCH_INSTITUTIONS_SUCCESS';
export const FETCH_INSTITUTIONS_FAILURE = 'FETCH_INSTITUTIONS_FAILURE';

export const DELETE_INSTITUTION_REQUEST = 'DELETE_INSTITUTION_REQUEST';
export const DELETE_INSTITUTION_SUCCESS = 'DELETE_INSTITUTION_SUCCESS';
export const DELETE_INSTITUTION_FAILURE = 'DELETE_INSTITUTION_FAILURE';
