export const FETCH_INSTITUTIONS_REQUEST = 'FETCH_INSTITUTIONS_REQUEST';
export const FETCH_INSTITUTIONS_SUCCESS = 'FETCH_INSTITUTIONS_SUCCESS';
export const FETCH_INSTITUTIONS_FAILURE = 'FETCH_INSTITUTIONS_FAILURE';
